version: '3.7'
services:
  db:           #コンテナの名前(なんでもok)
    image: mysql:5.7
    volumes:
      - "./db/mysql-data:/var/lib/mysql"
                   #ローカルのmysql-dataにデータを保存する（コンテナが消えてもデータが残る）
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  app:               #コンテナの名前(なんでもok)
    build: .         #Dockefileを指定
    volumes:         #dockerコンテナ内のファイルをローカルで編集する為の記述
      - ".:/app"
      - gem_data:/usr/local/bundle
                     #gemの永続化
    ports:           #localhost:3000にアクセスすると、コンテナ内の3000ポートにアクセスする
      - "3000:3000"
    tty: true
    depends_on:
      - db            #mysqlコンテナにアクセスする
    working_dir: "/app" #コンテナに入った時に直接appディレクトリに入る

volumes:
  mysql-data:
  gem_data: