default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: circle_app_v1_development


test:
  <<: *default
  database: circle_app_v1_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5